import Foundation
struct ItemDetail : Codable {
    let id : String?
    let site_id : String?
    let title : String?
    let subtitle : String?
    let seller_id : Int?
    let category_id : String?
    let official_store_id : Int?
    let price : Double?
    let base_price : Double?
    let original_price : Double?
    let currency_id : String?
    let initial_quantity : Int?
    let available_quantity : Int?
    let sold_quantity : Int?
    let sale_terms : [SaleTermsItem]?
    let buying_mode : String?
    let listing_type_id : String?
    let start_time : String?
    let stop_time : String?
    let condition : String?
    let permalink : String?
    let thumbnail_id : String?
    let thumbnail : String?
    let secure_thumbnail : String?
    let pictures : [PicturesItem]?
    let video_id : String?
    let descriptions : [String]?
    let accepts_mercadopago : Bool?
    let non_mercado_pago_payment_methods : [String]?
    let shipping : ShippingItem?
    let international_delivery_mode : String?
    let seller_address : SellerAddressItem?
    let seller_contact : String?
    let location : LocationItem?
    let coverage_areas : [String]?
//    let attributes : [AttributesItem]?
    let warnings : [String]?
    let listing_source : String?
    let variations : [VariationsItem]?
    let status : String?
    let sub_status : [String]?
    let tags : [String]?
    let warranty : String?
    let catalog_product_id : String?
    let domain_id : String?
    let parent_item_id : String?
    let differential_pricing : String?
    let deal_ids : [String]?
    let automatic_relist : Bool?
    let date_created : String?
    let last_updated : String?
    let health : Double?
    let catalog_listing : Bool?
    let channels : [String]?
}
